In [77]:
# 1. Importation de la librairie pandas 
import pandas as pd

In [78]:
# 2. Importation du fichier csv 

df = pd.read_csv("Exercices_Pandas_athlete_events.csv",encoding="cp1252")

In [79]:
# 3. Afficher les 5 premières lignes afin de voir si l'importation est correcte  
df.head()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN

In [80]:
# 4. Afficher les 5 dernières lignes  
df.tail()

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [81]:
# 5. Afficher les informations sur le dataframe (le nombre de lignes, de colonnes, le 
# nombre de NaN, le type de colonne)  
display(50*'-')
display("Nbre colonnes : ",len(df.columns))
display(50*'-')
display("Nbre lignes : ", df.shape[0])
display(50*'-')
display("Types par colonne :\n",df.dtypes)
display(50*'-')
display("nombre de NaN : ", df.isna().sum().sum() )

'--------------------------------------------------'

'Nbre colonnes : '

15

'--------------------------------------------------'

'Nbre lignes : '

271116

'--------------------------------------------------'

'Types par colonne :\n'

ID          int64
Name          str
Sex           str
Age       float64
Height    float64
Weight    float64
Team          str
NOC           str
Games         str
Year        int64
Season        str
City          str
Sport         str
Event         str
Medal         str
dtype: object

'--------------------------------------------------'

'nombre de NaN : '

np.int64(363853)

In [82]:
# 6. Afficher les dimensions du dataframe  
display("Dimensions de ma df : ", df.shape)

'Dimensions de ma df : '

(271116, 15)

In [83]:
# 7. Afficher les statistiques descriptives du dataframe 
display("Statistiques descriptives de ma df : ", df.describe())

'Statistiques descriptives de ma df : '

,ID,Age,Height,Weight,Year
count,271116.000000,261642.000000,210945.000000,208241.000000,271116.000000
mean,68248.954396,25.556898,175.338970,70.702393,1978.378480
std,39022.286345,6.393561,10.518462,14.348020,29.877632
min,1.000000,10.000000,127.000000,25.000000,1896.000000
25%,34643.000000,21.000000,168.000000,60.000000,1960.000000
50%,68205.000000,24.000000,175.000000,70.000000,1988.000000
75%,102097.250000,28.000000,183.000000,79.000000,2002.000000
max,135571.000000,97.000000,226.000000,214.000000,2016.000000

In [84]:
# 8. Compter le nombre de valeurs nulles dans le dataframe 
print("nombre de NaN : ", df.isna().sum().sum() )

nombre de NaN :  363853

In [85]:
# 9. Sélectionner la colonne Games et l'afficher (selon 2-3 manières) 
df["Games"]
display(df["Games"].head())
df["Games"].tail()

0    1992 Summer
1    2012 Summer
2    1920 Summer
3    1900 Summer
4    1988 Winter
Name: Games, dtype: str

271111    1976 Winter
271112    2014 Winter
271113    2014 Winter
271114    1998 Winter
271115    2002 Winter
Name: Games, dtype: str

In [92]:
# 10. Sélectionner la colonne Name et afficher le résultat en triant par ordre 
# alphabétique 
df["Name"] = df["Name"].str.strip()
df.loc[:,["Name"]].sort_values(by=["Name"])

# Problème d'encodage dans le csv

                            Name
0                      A Dijiang
1                       A Lamusi
153340  A. Aanantha Sambu Mayavo
528              A. Abdul Razzak
529              A. Abdul Razzak
...                          ...
114964                 zlem Kaya
79870                 zman Graud
207676                zzet Safer
102956                  zzet nce
102955                  zzet nce

[271116 rows x 1 columns]

In [96]:
# 11. Sélectionner les colonnes Event, City, Name, Medal 
df[["Event","City","Name",'Medal']]

,Event,City,Name,Medal
0,Basketball Men's Basketball,Barcelona,A Dijiang,NaN
1,Judo Men's Extra-Lightweight,London,A Lamusi,NaN
2,Football Men's Football,Antwerpen,Gunnar Nielsen Aaby,NaN
3,Tug-Of-War Men's Tug-Of-War,Paris,Edgar Lindenau Aabye,Gold
4,Speed Skating Women's 500 metres,Calgary,Christine Jacoba Aaftink,NaN
...,...,...,...,...
271111,Luge Mixed (Men)'s Doubles,Innsbruck,Andrzej ya,NaN
271112,"Ski Jumping Men's Large Hill, Individual",Sochi,Piotr ya,NaN
271113,"Ski Jumping Men's Large Hill, Team",Sochi,Piotr ya,NaN
271114,Bobsleigh Men's Four,Nagano,Tomasz Ireneusz ya,NaN
271115,Bobsleigh Men's Four,Salt Lake City,Tomasz Ireneusz ya,NaN

In [98]:
# 12. Slicer les lignes de 0 à 25 du dataframe au moyen du `iloc` 
df.iloc[0:26]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
5,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
6,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN
7,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
8,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,Speed Skating Women's 500 metres,NaN
9,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
10,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
11,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
12,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
13,6,Per Knut Aaland,M,31.0,188.0,75.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
14,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
15,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 30 kilometres,NaN
16,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
17,6,Per Knut Aaland,M,33.0,188.0,75.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
18,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
19,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
20,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
21,7,John Aalberg,M,31.0,183.0,72.0,United States,USA,1992 Winter,1992,Winter,Albertville,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN
22,7,John Aalberg,M,33.0,183.0,72.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10 kilometres,NaN
23,7,John Aalberg,M,33.0,183.0,72.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 30 kilometres,NaN
24,7,John Aalberg,M,33.0,183.0,72.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 10/15 kilometres Pu...,NaN
25,7,John Aalberg,M,33.0,183.0,72.0,United States,USA,1994 Winter,1994,Winter,Lillehammer,Cross Country Skiing,Cross Country Skiing Men's 4 x 10 kilometres R...,NaN

In [111]:
# 13. Filtrer la discipline Football de 2 manières différentes 

# A : Création d'un masque booléen
foot_mask = df['Sport']=="Football"
display(df[foot_mask])

# Ou directement

display(df[df['Sport'] == "Football"])
# B 
df_filtre = df[df["Sport"].isin(["Football"])]
df_filtre

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
105,37,Ann Kristin Aarnes,F,23.0,182.0,64.0,Norway,NOR,1996 Summer,1996,Summer,Atlanta,Football,Football Women's Football,Bronze
116,41,Rolf Aas,M,28.0,NaN,NaN,Norway,NOR,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
157,61,Stefan Abadzhiev,M,26.0,175.0,72.0,Bulgaria,BUL,1960 Summer,1960,Summer,Roma,Football,Football Men's Football,NaN
178,76,Jouan Patrice Abanda Etong,M,22.0,185.0,82.0,Cameroon,CMR,2000 Summer,2000,Summer,Sydney,Football,Football Men's Football,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270810,135438,Manuel Ziga Fernndez,M,20.0,172.0,69.0,Spain,ESP,1980 Summer,1980,Summer,Moskva,Football,Football Men's Football,NaN
270843,135455,Vjekoslav upani,M,19.0,NaN,NaN,Yugoslavia,YUG,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
270901,135476,Emily Jane Zurrer,F,21.0,179.0,69.0,Canada,CAN,2008 Summer,2008,Summer,Beijing,Football,Football Women's Football,NaN
270982,135504,Viktor Oleksandrovych Zviahintsev,M,25.0,178.0,79.0,Soviet Union,URS,1976 Summer,1976,Summer,Montreal,Football,Football Men's Football,Bronze
271107,135566,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States,USA,1972 Summer,1972,Summer,Munich,Football,Football Men's Football,NaN

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
105,37,Ann Kristin Aarnes,F,23.0,182.0,64.0,Norway,NOR,1996 Summer,1996,Summer,Atlanta,Football,Football Women's Football,Bronze
116,41,Rolf Aas,M,28.0,NaN,NaN,Norway,NOR,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
157,61,Stefan Abadzhiev,M,26.0,175.0,72.0,Bulgaria,BUL,1960 Summer,1960,Summer,Roma,Football,Football Men's Football,NaN
178,76,Jouan Patrice Abanda Etong,M,22.0,185.0,82.0,Cameroon,CMR,2000 Summer,2000,Summer,Sydney,Football,Football Men's Football,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270810,135438,Manuel Ziga Fernndez,M,20.0,172.0,69.0,Spain,ESP,1980 Summer,1980,Summer,Moskva,Football,Football Men's Football,NaN
270843,135455,Vjekoslav upani,M,19.0,NaN,NaN,Yugoslavia,YUG,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
270901,135476,Emily Jane Zurrer,F,21.0,179.0,69.0,Canada,CAN,2008 Summer,2008,Summer,Beijing,Football,Football Women's Football,NaN
270982,135504,Viktor Oleksandrovych Zviahintsev,M,25.0,178.0,79.0,Soviet Union,URS,1976 Summer,1976,Summer,Montreal,Football,Football Men's Football,Bronze
271107,135566,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States,USA,1972 Summer,1972,Summer,Munich,Football,Football Men's Football,NaN

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
105,37,Ann Kristin Aarnes,F,23.0,182.0,64.0,Norway,NOR,1996 Summer,1996,Summer,Atlanta,Football,Football Women's Football,Bronze
116,41,Rolf Aas,M,28.0,NaN,NaN,Norway,NOR,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
157,61,Stefan Abadzhiev,M,26.0,175.0,72.0,Bulgaria,BUL,1960 Summer,1960,Summer,Roma,Football,Football Men's Football,NaN
178,76,Jouan Patrice Abanda Etong,M,22.0,185.0,82.0,Cameroon,CMR,2000 Summer,2000,Summer,Sydney,Football,Football Men's Football,Gold
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
270810,135438,Manuel Ziga Fernndez,M,20.0,172.0,69.0,Spain,ESP,1980 Summer,1980,Summer,Moskva,Football,Football Men's Football,NaN
270843,135455,Vjekoslav upani,M,19.0,NaN,NaN,Yugoslavia,YUG,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
270901,135476,Emily Jane Zurrer,F,21.0,179.0,69.0,Canada,CAN,2008 Summer,2008,Summer,Beijing,Football,Football Women's Football,NaN
270982,135504,Viktor Oleksandrovych Zviahintsev,M,25.0,178.0,79.0,Soviet Union,URS,1976 Summer,1976,Summer,Montreal,Football,Football Men's Football,Bronze
271107,135566,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States,USA,1972 Summer,1972,Summer,Munich,Football,Football Men's Football,NaN

In [115]:
# 14. Filtrer le dataframe sur la saison Summer et stocker les lignes dans une nouvelle 
# variable appelée `ete` 
ete = df[df["Season"]=="Summer"]
ete

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
0,1,A Dijiang,M,24.0,180.0,80.0,China,CHN,1992 Summer,1992,Summer,Barcelona,Basketball,Basketball Men's Basketball,NaN
1,2,A Lamusi,M,23.0,170.0,60.0,China,CHN,2012 Summer,2012,Summer,London,Judo,Judo Men's Extra-Lightweight,NaN
2,3,Gunnar Nielsen Aaby,M,24.0,NaN,NaN,Denmark,DEN,1920 Summer,1920,Summer,Antwerpen,Football,Football Men's Football,NaN
3,4,Edgar Lindenau Aabye,M,34.0,NaN,NaN,Denmark/Sweden,DEN,1900 Summer,1900,Summer,Paris,Tug-Of-War,Tug-Of-War Men's Tug-Of-War,Gold
26,8,"Cornelia ""Cor"" Aalten (-Strannood)",F,18.0,168.0,NaN,Netherlands,NED,1932 Summer,1932,Summer,Los Angeles,Athletics,Athletics Women's 100 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271106,135565,Fernando scar Zylberberg,M,27.0,168.0,76.0,Argentina,ARG,2004 Summer,2004,Summer,Athina,Hockey,Hockey Men's Hockey,NaN
271107,135566,"James Francis ""Jim"" Zylker",M,21.0,175.0,75.0,United States,USA,1972 Summer,1972,Summer,Munich,Football,Football Men's Football,NaN
271108,135567,Aleksandr Viktorovich Zyuzin,M,24.0,183.0,72.0,Russia,RUS,2000 Summer,2000,Summer,Sydney,Rowing,Rowing Men's Lightweight Coxless Fours,NaN
271109,135567,Aleksandr Viktorovich Zyuzin,M,28.0,183.0,72.0,Russia,RUS,2004 Summer,2004,Summer,Athina,Rowing,Rowing Men's Lightweight Coxless Fours,NaN
271110,135568,Olga Igorevna Zyuzkova,F,33.0,171.0,69.0,Belarus,BLR,2016 Summer,2016,Summer,Rio de Janeiro,Basketball,Basketball Women's Basketball,NaN

In [116]:
# 15. Filtrer le dataframe sur la saison Winter et stocker les lignes dans une nouvelle 
# variable appelée `hiver`
hiver = df[df["Season"]=="Winter"]
hiver

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
4,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,Speed Skating Women's 500 metres,NaN
5,5,Christine Jacoba Aaftink,F,21.0,185.0,82.0,Netherlands,NED,1988 Winter,1988,Winter,Calgary,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
6,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,Speed Skating Women's 500 metres,NaN
7,5,Christine Jacoba Aaftink,F,25.0,185.0,82.0,Netherlands,NED,1992 Winter,1992,Winter,Albertville,Speed Skating,"Speed Skating Women's 1,000 metres",NaN
8,5,Christine Jacoba Aaftink,F,27.0,185.0,82.0,Netherlands,NED,1994 Winter,1994,Winter,Lillehammer,Speed Skating,Speed Skating Women's 500 metres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271111,135569,Andrzej ya,M,29.0,179.0,89.0,Poland-1,POL,1976 Winter,1976,Winter,Innsbruck,Luge,Luge Mixed (Men)'s Doubles,NaN
271112,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Individual",NaN
271113,135570,Piotr ya,M,27.0,176.0,59.0,Poland,POL,2014 Winter,2014,Winter,Sochi,Ski Jumping,"Ski Jumping Men's Large Hill, Team",NaN
271114,135571,Tomasz Ireneusz ya,M,30.0,185.0,96.0,Poland,POL,1998 Winter,1998,Winter,Nagano,Bobsleigh,Bobsleigh Men's Four,NaN
271115,135571,Tomasz Ireneusz ya,M,34.0,185.0,96.0,Poland,POL,2002 Winter,2002,Winter,Salt Lake City,Bobsleigh,Bobsleigh Men's Four,NaN

In [118]:
# 16. Afficher de manière unique tous les sports 
df["Sport"].unique()

<StringArray>
[               'Basketball',                      'Judo',
                  'Football',                'Tug-Of-War',
             'Speed Skating',      'Cross Country Skiing',
                 'Athletics',                'Ice Hockey',
                  'Swimming',                 'Badminton',
                   'Sailing',                  'Biathlon',
                'Gymnastics',          'Art Competitions',
             'Alpine Skiing',                  'Handball',
             'Weightlifting',                 'Wrestling',
                      'Luge',                'Water Polo',
                    'Hockey',                    'Rowing',
                 'Bobsleigh',                   'Fencing',
             'Equestrianism',                  'Shooting',
                    'Boxing',                 'Taekwondo',
                   'Cycling',                    'Diving',
                  'Canoeing',                    'Tennis',
         'Modern Pentathlon',            'Figure Skating',
                      'Golf',                  'Softball',
                   'Archery',                'Volleyball',
     'Synchronized Swimming',              'Table Tennis',
           'Nordic Combined',                  'Baseball',
       'Rhythmic Gymnastics',          'Freestyle Skiing',
              'Rugby Sevens',              'Trampolining',
          'Beach Volleyball',                 'Triathlon',
               'Ski Jumping',                   'Curling',
              'Snowboarding',                     'Rugby',
 'Short Track Speed Skating',                  'Skeleton',
                  'Lacrosse',                      'Polo',
                   'Cricket',                  'Racquets',
              'Motorboating',       'Military Ski Patrol',
                   'Croquet',              'Jeu De Paume',
                     'Roque',                  'Alpinism',
             'Basque Pelota',               'Aeronautics']
Length: 66, dtype: str

In [140]:
# 17. Filtrer les lignes pour récupérer les athlètes ayant dans leur nom "Owens" ou "Jesse" et stocker cela dans une nouvelle variable 
Owens_jesse = df[df["Name"].str.contains("Jesse") | df["Name"].str.contains("Owens")]
print("Nbre owens jesse : ", Owens_jesse.shape[0])
Owens_jesse

Nbre owens jesse :  98

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
14038,7587,"Kenneth Owens ""Ken"" Bantum",M,21.0,198.0,106.0,United States,USA,1956 Summer,1956,Summer,Melbourne,Athletics,Athletics Men's Shot Put,NaN
35531,18266,"Jesse Landis ""Lee"" Carleton",M,41.0,NaN,NaN,United States,USA,1904 Summer,1904,Summer,St. Louis,Golf,Golf Men's Individual,NaN
35532,18266,"Jesse Landis ""Lee"" Carleton",M,41.0,NaN,NaN,United States Golf Association-3,USA,1904 Summer,1904,Summer,St. Louis,Golf,Golf Men's Team,Bronze
43016,22182,Jesse Cockney,M,24.0,180.0,76.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Cross Country Skiing,Cross Country Skiing Men's Sprint,NaN
43017,22182,Jesse Cockney,M,24.0,180.0,76.0,Canada,CAN,2014 Winter,2014,Winter,Sochi,Cross Country Skiing,Cross Country Skiing Men's 50 kilometres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
256091,128225,Jesse Alfred Wallingford,M,36.0,NaN,NaN,Great Britain,GBR,1908 Summer,1908,Summer,London,Shooting,"Shooting Men's Free Rifle, Three Positions, 30...",NaN
256092,128225,Jesse Alfred Wallingford,M,36.0,NaN,NaN,Great Britain,GBR,1908 Summer,1908,Summer,London,Shooting,"Shooting Men's Free Rifle, Three Positions, 30...",NaN
260999,130612,Jesse Daniel Williams,M,24.0,184.0,80.0,United States,USA,2008 Summer,2008,Summer,Beijing,Athletics,Athletics Men's High Jump,NaN
261000,130612,Jesse Daniel Williams,M,28.0,184.0,80.0,United States,USA,2012 Summer,2012,Summer,London,Athletics,Athletics Men's High Jump,NaN
262755,131475,Harvey Jesse Wood,M,23.0,193.0,89.0,England-1,GBR,1908 Summer,1908,Summer,London,Hockey,Hockey Men's Hockey,Gold

In [146]:

# 18. Compter combien il y a de femmes et d'hommes dans le dataframe  
nbre_homme = df[df["Sex"]=="M"]
nbre_femme = df[df["Sex"]== "F"]

print("Nombre d'homme : ", nbre_homme.shape[0], "\n Nombre de femmes : ", nbre_femme.shape[0])

print("Nombre d'homme + femmes est-il égal au nbre total de personnes ? ", nbre_femme.shape[0] + nbre_homme.shape[0] == df.shape[0])

Nombre d'homme :  196594
 Nombre de femmes :  74522
Nombre d'homme + femmes est-il égal au nbre total de personnes ?  True

In [159]:
# 19. Quel est l'athlète le plus jeune ? 
athlete_le_plus_jeune = df["Age"].min()
athlete_le_plus_jeune
# 20. Quel est l'athlète le plus vieux ? 
athlete_le_plus_vieux = df["Age"].max()
athlete_le_plus_vieux

display(df["Age"].sort_values().head(50))

142882    10.0
140650    11.0
94058     11.0
252230    11.0
101378    11.0
252233    11.0
79024     11.0
43468     11.0
73461     11.0
252232    11.0
252231    11.0
237141    11.0
102916    11.0
152798    11.0
9649      12.0
192507    12.0
84361     12.0
46955     12.0
108031    12.0
168942    12.0
148942    12.0
50292     12.0
236977    12.0
251495    12.0
96665     12.0
97086     12.0
126542    12.0
149033    12.0
60911     12.0
249803    12.0
9648      12.0
9650      12.0
50291     12.0
50293     12.0
50294     12.0
168941    12.0
145150    12.0
85840     12.0
96236     12.0
79352     12.0
91911     12.0
93850     12.0
120234    12.0
91910     12.0
120233    12.0
91912     12.0
226019    12.0
253662    12.0
91913     12.0
197895    12.0
Name: Age, dtype: float64

In [196]:
# 21. Quels sont les joueurs ayant gagné des médailles d'Or en badminton simple au cours des années ? Trier le résultat par ordre alphabétique sur le nom des joueurs. 
badminton = (df[df["Sport"]=="Badminton"])
badminton_single_medals = badminton[df["Event"].str.contains("Singles")]
badminton_single_medals = badminton[badminton["Medal"].isin(["Gold","Silver","Bronze"]) ]
badminton_single_medals

C:\Users\e.vervaeren\AppData\Local\Temp\ipykernel_11664\4260988149.py:3: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  badminton_single_medals = badminton[df["Event"].str.contains("Singles")]

,ID,Name,Sex,Age,Height,Weight,Team,NOC,Games,Year,Season,City,Sport,Event,Medal
2453,1374,Tontowi Ahmad,M,29.0,179.0,72.0,Indonesia-1,INA,2016 Summer,2016,Summer,Rio de Janeiro,Badminton,Badminton Mixed Doubles,Gold
8956,4921,Simon David Archer,M,27.0,189.0,86.0,Great Britain-2,GBR,2000 Summer,2000,Summer,Sydney,Badminton,Badminton Mixed Doubles,Bronze
9159,5040,Antonius Budi Ariantho,M,24.0,170.0,66.0,Indonesia-1,INA,1996 Summer,1996,Summer,Atlanta,Badminton,Badminton Men's Doubles,Bronze
11293,6174,Viktor Axelsen,M,22.0,194.0,88.0,Denmark,DEN,2016 Summer,2016,Summer,Rio de Janeiro,Badminton,Badminton Men's Singles,Bronze
13854,7504,Bang Su-Hyeon,F,19.0,NaN,NaN,South Korea,KOR,1992 Summer,1992,Summer,Barcelona,Badminton,Badminton Women's Singles,Silver
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269012,134597,Zhang Yawen,F,23.0,162.0,58.0,China-2,CHN,2008 Summer,2008,Summer,Beijing,Badminton,Badminton Women's Doubles,Bronze
269148,134683,Zhao Yunlei,F,25.0,173.0,60.0,China-1,CHN,2012 Summer,2012,Summer,London,Badminton,Badminton Mixed Doubles,Gold
269149,134683,Zhao Yunlei,F,25.0,173.0,60.0,China-1,CHN,2012 Summer,2012,Summer,London,Badminton,Badminton Women's Doubles,Gold
269150,134683,Zhao Yunlei,F,29.0,173.0,60.0,China-1,CHN,2016 Summer,2016,Summer,Rio de Janeiro,Badminton,Badminton Mixed Doubles,Bronze
269395,134802,Zhou Mi,F,25.0,175.0,65.0,China,CHN,2004 Summer,2004,Summer,Athina,Badminton,Badminton Women's Singles,Bronze

In [228]:
# 22. Quels sont les 3 pays ayant gagné le plus de médailles de 1984 à 2016 ? 

# Filtrer les athletes medialles
medailles = df[df["Medal"].notna()]

# garder 1 athlète par event par pays et par année
medailles = medailles[["Year","Event","NOC","Medal"]].drop_duplicates()
display(medailles.sort_values(by="Event"))

# Grouper les pays en comptant le nbre de medailles
medailles = medailles.groupby(by="NOC")["Medal"].count().rename("Nb_Medailles").sort_values()
medailles

        Year                                      Event  NOC   Medal
214105  1936              Aeronautics Mixed Aeronautics  SUI    Gold
198803  1998               Alpine Skiing Men's Combined  AUT    Gold
252745  2014               Alpine Skiing Men's Combined  SUI    Gold
195965  2002               Alpine Skiing Men's Combined  AUT  Bronze
120535  1994               Alpine Skiing Men's Combined  NOR    Gold
...      ...                                        ...  ...     ...
132537  2016  Wrestling Women's Middleweight, Freestyle  KAZ  Bronze
114840  2016  Wrestling Women's Middleweight, Freestyle  JPN    Gold
114017  2008  Wrestling Women's Middleweight, Freestyle  RUS  Silver
254114  2012  Wrestling Women's Middleweight, Freestyle  RUS  Bronze
108583  2012  Wrestling Women's Middleweight, Freestyle  CHN  Silver

[18905 rows x 4 columns]

NOC
AFG     2
AHO     1
ALG    17
ANZ    12
ARG    74
       ..
VIE     4
WIF     2
YUG    87
ZAM     2
ZIM     8
Name: Nb_Medailles, Length: 149, dtype: int64