**<p style="text-align:center; font-size:30px"><u> Exercices de base numpy</u></p>**

# Exercice 1
- créez un numpy array depuis la liste suivante [11.7, 20, 325, 10.2, 11.7, 20]
- remplacez la première occurence de la valeur 11.7 par 5
- remplacez toutes les occurences des valeurs 20 par 0
- calculez la taille (mémoire) du tableau
- modifier le typage en uint8
- calculez la taille du tableau
- Observez les valeurs ? Que s'est-il passé ?

<br>

In [166]:
import numpy as np 

arr1 = np.array([11.7, 20, 325, 10.2, 11.7, 20])
arr1[0] = 5

# OU
arr1 = np.array([11.7, 20, 325, 10.2, 11.7, 20])
arr1_bool_mask = arr1 == 11.7

arr1_modify_first_occur = arr1[arr1_bool_mask]
arr1_modify_first_occur[0] = 5

print(arr1_modify_first_occur)

print(arr1)

#  OU

arr_1 = arr1 = np.array([11.7, 20, 325, 10.2, 11.7, 20])
arr1[np.where(arr1==11.7)[0][0]] = 5

display("ay {}".format(arr1))

# utiliser le masquage booléan OU np.where(cond, if true, if false)
arr1 = np.where(arr1==20, arr1*0, arr1)
display(arr1)
print("taille mémoire : ",arr1.nbytes)
display(arr1.size)
arr1  = arr1.astype(np.uint8)
print("taille mémoire : ",arr1.nbytes)

# La taille mémoire est 8x plus petite (elle doit être en 64 par défaut)

[ 5.  11.7]
[ 11.7  20.  325.   10.2  11.7  20. ]

'ay [  5.   20.  325.   10.2  11.7  20. ]'

array([  5. ,   0. , 325. ,  10.2,  11.7,   0. ])

taille mémoire :  48

6

taille mémoire :  6

# Exercice 2

- créez un numpy array depuis la matrice suivante [[1, 2, 3],  [4, 5, 6], [7, 8, np.nan]]
- affichez:
  - le type de données de la matrice
  - sa forme
  - son nombre de dimension
  - son nombre d'élément
  - Depuis la forme, pouvez-vous obtenir le nombre de dimension et le nombre d'élément ?
- multipliez la dernière colonne par 5 et divisez la première ligne par 0
- modifier le typage en int. Que se passe-t-il ?

<br>

In [50]:
arr2 = np.array([[1, 2, 3],  [4, 5, 6], [7, 8, np.nan]])
display(arr2)
print("type de donnée :",arr2.dtype)
print("forme de l'array : ", arr2.shape)
print("nbre dimension : ",arr2.ndim)
print("nbre éléments: ", arr2.size)
print(f"depuis la forme, nbre de dimension = {len(arr2.shape)} et nbre d'éléments = {arr2.shape[0]*arr2.shape[1]}")
arr2[:,-1] *= 5  # Mutiplier la dernière colonne par 5

arr2[0] /= 0 # Diviser la première ligne par 0

print(arr2)

arr2= arr2.astype(np.int32) # Lorsque je transforme le type de l'array en int, les infinites et nan deviennes des nbres négatifs

arr2

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8., nan]])

type de donnée : float64
forme de l'array :  (3, 3)
nbre dimension :  2
nbre éléments:  9
depuis la forme, nbre de dimension = 2 et nbre d'éléments = 9
[[inf inf inf]
 [ 4.  5. 30.]
 [ 7.  8. nan]]

C:\Users\e.vervaeren\AppData\Local\Temp\ipykernel_13708\2448591453.py:10: RuntimeWarning: divide by zero encountered in divide
  arr2[0] /= 0 # Diviser la première ligne par 0
C:\Users\e.vervaeren\AppData\Local\Temp\ipykernel_13708\2448591453.py:14: RuntimeWarning: invalid value encountered in cast
  arr2= arr2.astype(np.int32)

array([[-2147483648, -2147483648, -2147483648],
       [          4,           5,          30],
       [          7,           8, -2147483648]], dtype=int32)

# Exercice 3

Exercice:
1. Créer la matrice suivante dans la variable x1:
  ```py
      [[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]]
````

2. Extraire une partie de x1 dans la variable x2
  ```py
      [[50, 60],
       [80, 90]]
````
3. Remplacer le 50 de x2 par 99
4. Réafficher x1

In [157]:
x1 = np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
x2 = x1[1:,1:]

x2[x2 == 50] = 99

display(x2)
print(x1)

array([[99, 60],
       [80, 90]])

[[10 20 30]
 [40 99 60]
 [70 80 90]]

# Exercice 4

Exercice:
1. Créer la matrice suivante dans la variable x3:
  ```py
      [[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]]
````

2. Extraire __une copie__ d'une partie de x3 dans la variable x4
  ```py
      [[50, 60],
       [80, 90]]
````
3. Remplacer le 50 de x4 par 99
4. Réafficher x3

In [159]:
x3 = np.array([10,20,30,40,50,60,70,80,90]).reshape(3,3)
x4 = x3[1:,1:].copy()
x4[x4 == 50] = 99

display(x3)
display(x4)

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

array([[99, 60],
       [80, 90]])

# Exercice 5

- créez une matrice (4*4) remplie de valeurs aléatoires comprises entre 2 et 8
- créer un matrice d'identité (*i.e.* une matrice carrée dont la diagonale descendente principale est remplie de 1 et le reste = 0). Proposez plusieurs solutions
- créer une matrice dont la diagonale principale sera remplie de 6 valeurs aléatoires. Proposez plusieurs solutions

(tip: 'zeros','identity', 'fill_diagonal')
<br>

In [111]:
arr5 = np.random.randint(2,9,16).reshape(4,4)


arr_identity1 = np.identity(4)
arr_identity2 = np.eye(3, dtype=int)
arr_identity3 = np.diag([1,1,1,1])
arr_identity1
arr_identity2
arr_identity3

# Diagonale méthode 1
arr_diag = np.diag(np.random.randint(1,100,6))

# Diagonale méthode 2
arr_diag2 = np.eye(6, dtype=int)

#Diagonale méthode 3 np.fill_diagonal(array, fill list)
arr_diag3 = np.array([num*0 for num in range(36)]).reshape(6,6)
np.fill_diagonal(arr_diag3,np.random.randint(1, 100, 6))
display(arr_diag3)

array([[ 9,  0,  0,  0,  0,  0],
       [ 0, 15,  0,  0,  0,  0],
       [ 0,  0, 92,  0,  0,  0],
       [ 0,  0,  0, 69,  0,  0],
       [ 0,  0,  0,  0,  4,  0],
       [ 0,  0,  0,  0,  0,  2]])

# Exercice 6

- reproduire la matrice suivante (sans les noms de lignes ou colonnes)
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>pâtes</th>
      <th>légumes</th>
      <th>divers</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>bob</th>
      <td>10€</td>
      <td>30€</td>
      <td>5€</td>
    </tr>
    <tr>
      <th>alice</th>
      <td>20€</td>
      <td>50€</td>
      <td>1€</td>
    </tr>
    <tr>
      <th>john</th>
      <td>15€</td>
      <td>30€</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>

- affichez le montant total des achats
- affichez les totaux des achats par personne
- affichez les moyennes des achats par type d'aliments

<br>

In [123]:
spendings = np.array([10,30,5,20,50,1,15,30,np.nan]).reshape(3,3)
display()
print(f"total amount spend = {np.nansum(spendings)}")   

# Afficher les totaux par lignes => agreg(1) ?

print(f"Total spent by person : {np.nansum(spendings,axis=1,keepdims=True)}")

# Afficher les moyennes des achats par type d'aliments

print(f"Mean by items : {np.nanmean(spendings, axis=0, keepdims=True)}")

total amount spend = 161.0
Total spent by person : [[45.]
 [71.]
 [45.]]
Mean by items : [[15.         36.66666667  3.        ]]

# Exercice 7

Cette fois-ci nous avons les quantités achetées ainsi que le prix unitaires pour chacun des éléments

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>pâtes</th>
      <th>légumes</th>
      <th>divers</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>bob</th>
      <td>1</td>
      <td>4</td>
      <td>2</td>
    </tr>
    <tr>
      <th>alice</th>
      <td>3</td>
      <td>5</td>
      <td>7</td>
    </tr>
    <tr>
      <th>john</th>
      <td>5</td>
      <td>4</td>
      <td>4</td>
    </tr>
  </tbody>
</table>

```py
[20, 5, 3]
````

- calculez le montant total par personne
- calculez le montant total par produit

<br>

In [129]:
buyed_qtity = np.array([1,4,2,3,5,7,5,4,4]).reshape(3,3)
price_per_item = np.array([20,5,3])

spendings2 = buyed_qtity * price_per_item
display(spendings2)

# Montant total par personne : Aggregation des colonnes
print(f"Total spent per person : {np.nansum(spendings2, axis=1, keepdims=True)}")

# Montant total par produit, aggregation des lignes
print(f"Total per product : {np.nansum(spendings2, axis=0, keepdims=True)}")

array([[ 20,  20,   6],
       [ 60,  25,  21],
       [100,  20,  12]])

Total spent per person : [[ 46]
 [106]
 [132]]
Total per product : [[180  65  39]]

In [162]:
my_test_array = np.array([(x**2)%4 for x in range(1000)])
my_test_array

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1])